### PR TITLE
Added testing for EventsController, modified EventsController methods 

### PR DESCRIPTION
**Pull request by serbanlex**

### CODE REVIEW

**Comment by danpercic86** [comment]
Your branch is based on Contact branch and has all changes that Andreas made there. Please **rebase** your branch into  **dev** branch and push again, without closing this pull request

**Review by danpercic86 — CHANGES_REQUESTED** [review]
Rebase into dev

**Comment by serbanlex** [comment]
I think I rebased it, is the git part ok now?

**Comment by danpercic86** [comment]
Well, not really, you still have commits from other Contact branch. Let me try something

**Comment by danpercic86** [comment]
It looks much better now, but tests are failing. Before coding, hard reset your local `events-testing` branch into `events-testing` from remote origin. 
Please run tests locally using `dotnet test` command and fix failing tests

**Review by danpercic86 — APPROVED** [review]

**Pull request merged**
